/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihannetbeans;

/**
 *
 * @author dell
 */
public class Modul5tugas extends javax.swing.JFrame {

    /**
     * Creates new form Modul5tugas
     */
    public Modul5tugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        Gbt_Makanan = new javax.swing.ButtonGroup();
        Gbt_Minuman = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbSeblak = new javax.swing.JCheckBox();
        cbBakso = new javax.swing.JCheckBox();
        cbMie = new javax.swing.JCheckBox();
        cbSate = new javax.swing.JCheckBox();
        cbJusjeruk = new javax.swing.JCheckBox();
        cbJusalpukat = new javax.swing.JCheckBox();
        cbLemontea = new javax.swing.JCheckBox();
        cbJusjambu = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        eNAMA = new javax.swing.JTextField();
        eALAMAT = new javax.swing.JTextField();
        bPesan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaPesan = new javax.swing.JTextArea();

        jCheckBox1.setText("jCheckBox1");

        jCheckBox8.setText("jCheckBox8");

        jCheckBox9.setText("jCheckBox9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NAMA");

        jLabel2.setText("ALAMAT");

        jLabel3.setText("MAKANAN");

        Gbt_Makanan.add(cbSeblak);
        cbSeblak.setSelected(true);
        cbSeblak.setText("Seblak");
        cbSeblak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeblakActionPerformed(evt);
            }
        });

        Gbt_Makanan.add(cbBakso);
        cbBakso.setText("Bakso");

        Gbt_Makanan.add(cbMie);
        cbMie.setText("Mie Goreng");

        Gbt_Makanan.add(cbSate);
        cbSate.setText("Sate Ayam");

        Gbt_Minuman.add(cbJusjeruk);
        cbJusjeruk.setSelected(true);
        cbJusjeruk.setText("Jus Jeruk");
        cbJusjeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJusjerukActionPerformed(evt);
            }
        });

        Gbt_Minuman.add(cbJusalpukat);
        cbJusalpukat.setText("Jus Alpukat");

        Gbt_Minuman.add(cbLemontea);
        cbLemontea.setText("Lemon Tea");

        Gbt_Minuman.add(cbJusjambu);
        cbJusjambu.setText("Jus Jambu");
        cbJusjambu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJusjambuActionPerformed(evt);
            }
        });

        jLabel4.setText("MINUMAN");

        bPesan.setText("PESAN");
        bPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesanActionPerformed(evt);
            }
        });

        areaPesan.setColumns(20);
        areaPesan.setRows(5);
        jScrollPane1.setViewportView(areaPesan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMie)
                                    .addComponent(cbJusjeruk))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbSate)
                                            .addComponent(cbBakso)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(cbJusalpukat))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(eNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))
                            .addComponent(cbSeblak, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbLemontea)
                                .addGap(34, 34, 34)
                                .addComponent(cbJusjambu)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(bPesan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbSeblak)
                    .addComponent(cbBakso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSate)
                    .addComponent(cbMie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJusjeruk)
                    .addComponent(cbJusalpukat)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLemontea)
                    .addComponent(cbJusjambu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bPesan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSeblakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeblakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSeblakActionPerformed

    private void cbJusjerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJusjerukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJusjerukActionPerformed

    private void cbJusjambuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJusjambuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJusjambuActionPerformed

    private void bPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesanActionPerformed
        // TODO add your handling code here:
        int IndexCombo;
        String daftarMakanan="";
        String daftarMinuman="";
        if (cbSeblak.isSelected()){
            daftarMakanan +=cbSeblak.getText()+"";
        }if (cbBakso.isSelected()){
            daftarMakanan +=cbBakso.getText()+"";
        }
         if (cbMie.isSelected()){
            daftarMakanan +=cbMie.getText()+"";
        } if (cbSate.isSelected()){
            daftarMakanan +=cbSate.getText()+"";
        }
        if (cbJusjeruk.isSelected()){
            daftarMinuman +=cbJusjeruk.getText()+"";
        }if (cbJusalpukat.isSelected()){
            daftarMinuman +=cbJusalpukat.getText()+"";
        }
        if (cbLemontea.isSelected()){
            daftarMinuman +=cbLemontea.getText()+"";
        }
        if (cbJusjambu.isSelected()){
            daftarMinuman +=cbJusjambu.getText()+"";
        }
        areaPesan.setText(
            "NAMA :\t"+eNAMA.getText() + "\n"+
            "ALAMAT :\t"+eALAMAT.getText() + "\n"+
            "MAKANAN :\t"+ daftarMakanan + "\n"+
            "MINUMAN :\t"+ daftarMinuman + "\n"
        );
    }//GEN-LAST:event_bPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modul5tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modul5tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modul5tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modul5tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modul5tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Gbt_Makanan;
    private javax.swing.ButtonGroup Gbt_Minuman;
    private javax.swing.JTextArea areaPesan;
    private javax.swing.JButton bPesan;
    private javax.swing.JCheckBox cbBakso;
    private javax.swing.JCheckBox cbJusalpukat;
    private javax.swing.JCheckBox cbJusjambu;
    private javax.swing.JCheckBox cbJusjeruk;
    private javax.swing.JCheckBox cbLemontea;
    private javax.swing.JCheckBox cbMie;
    private javax.swing.JCheckBox cbSate;
    private javax.swing.JCheckBox cbSeblak;
    private javax.swing.JTextField eALAMAT;
    private javax.swing.JTextField eNAMA;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
